ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include
from list.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('user/', include('users.urls', namespace='users')),
    path('del/<int:pk>/', DeleteTask.as_view(), name="delete"),
    path('edit/<int:pk>/', UpdateTaskStatus.as_view(), name="update"),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('signin/', signin_user, name='signin'),
]

list/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Task(models.Model):
    task = models.CharField(max_length=200, verbose_name="Задача")
    status = models.ForeignKey("Status", on_delete=models.PROTECT, related_name="status",
                               verbose_name="Статус", default=1)
    user = models.ManyToManyField(User, related_name='user')

    def __str__(self):
        return self.task

    def get_absolute_url(self):
        return reverse('delete', kwargs={'pk': self.pk})


class Status(models.Model):
    status_name = models.CharField(max_length=100)

    def __str__(self):
        return self.status_name

users/models.py
from django.db import models

# Create your models here.

list/forms.py
from django import forms
from .models import *


class InputTaskForm(forms.ModelForm):
    task = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter a task here", "label": ''}), label='')

    class Meta:
        model = Task
        fields = ('task', )

users/forms.py
from django import forms


class RegistrationUserForm(forms.Form):
    username = forms.CharField(min_length=8, max_length=50)
    password = forms.CharField(min_length=8, max_length=50, widget=forms.PasswordInput())


class LoginUserForm(forms.Form):
    username = forms.CharField(min_length=8, max_length=50)
    password = forms.CharField(min_length=8, max_length=50, widget=forms.PasswordInput())

list/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, UpdateView

from .forms import *
from .models import *


def index(request):
    task = Task.objects.filter(status=1)
    if request.method == "POST":
        form = InputTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = InputTaskForm()
    return render(request, 'list/index.html', {"form": form, 'task': task})


class DeleteTask(DeleteView):
    model = Task
    template_name = 'list/index.html'
    success_url = reverse_lazy('home')


class UpdateTaskStatus(UpdateView):
    # model = Anime
    # fields = "__all__"
    form_class = Task
    template_name = 'list/index.html'
    success_url = reverse_lazy('home')

    def get_queryset(self):
        return Task.objects.all()

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
from list.models import Task


def login_user(request):
    if request.method == "POST":
        form = LoginUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            print(user.pk)

            if user and user.is_active:
                login(request, user)
                return redirect('home')
    else:
        form = LoginUserForm()
    return render(request, 'users/login.html', {"form": form})


def logout_user(request):
    logout(request)
    return redirect('home')


def signin_user(request):
    if request.method == "POST":
        form = RegistrationUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(username=cd['username'], password=cd['password'])
            user.save()
            return redirect('users:login')
    else:
        form = RegistrationUserForm()
    return render(request, 'users/signin.html', {"form": form})

list/templates/list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>To-do list</title>
  <link rel="stylesheet" href="style.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/js/bootstrap.bundle.min.js" integrity="sha512-igl8WEUuas9k5dtnhKqyyld6TzzRjvMqLC79jkgT3z02FvJyHAuUtyemm/P/jYSne1xwFI06ezQxEwweaiV7VA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'home' %}">To Do Web Site</a>
      {% if request.user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'home' %}">Welcome, {{ request.user.username }}</a>
      {% endif %}
    </div>
    <ul class="nav navbar-nav">
      {% if not request.user.is_authenticated %}
      <li><span><a href="{% url 'users:login' %}">Login</a></span></li>
      <li><span><a href="{% url 'users:signin' %}">Registration</a></span></li>
      {% else %}
      <li><span><a href="{% url 'users:logout' %}">Logout</a></span></li>
      {% endif %}
    </ul>
  </div>
</nav>

  <section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card rounded-3">
            <div class="card-body p-4">

              <h4 class="text-center my-3 pb-3">To Do App</h4>

              <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2" method="post">
                <div class="col-12">
                  <div class="form-outline">
                    <!-- <label class="form-label" for="form1">Enter a task here</label> -->
                    {% csrf_token %}
                    {{ form.as_div }}
<!--                    <input type="text" id="form1" class="form-control" placeholder="Enter a task here" />-->
                  </div>
                </div>

                <div class="col-12">
                  <button type="submit" class="btn btn-primary">Save</button>
                </div>

                <div class="col-12">
                  <button type="submit" class="btn btn-warning">Get tasks</button>
                </div>
              </form>

              <table class="table mb-4">
                <thead>
                  <tr>
                    <th scope="col">№</th>
                    <th scope="col">Todo item</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for i in task %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ i.task }}</td>
                    <td>{{ i.status.status_name }}</td>
                    <td>
                      <form action="del/{{ i.pk }}/" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" name="delete-task">Delete</button>
                        <button type="submit" class="btn btn-success ms-1" name="finished-task">Finished</button>
                      </form>
                    </td>
                  </tr>
                  {% endfor %}
<!--                  <tr>-->
<!--                    <th scope="row">2</th>-->
<!--                    <td>Renew car insurance</td>-->
<!--                    <td>In progress</td>-->
<!--                    <td>-->
<!--                      <button type="submit" class="btn btn-danger">Delete</button>-->
<!--                      <button type="submit" class="btn btn-success ms-1">Finished</button>-->
<!--                    </td>-->
<!--                  </tr>-->
<!--                  <tr>-->
<!--                    <th scope="row">3</th>-->
<!--                    <td>Sign up for online course</td>-->
<!--                    <td>In progress</td>-->
<!--                    <td>-->
<!--                      <button type="submit" class="btn btn-danger">Delete</button>-->
<!--                      <button type="submit" class="btn btn-success ms-1">Finished</button>-->
<!--                    </td>-->
<!--                  </tr>-->
                </tbody>
              </table>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
</html>

users/templates/users/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
  <h1>Login</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
</body>
</html>

users/templates/users/signin.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signin</title>
</head>
<body>
  <h1>Signin</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registration</button>
  </form>
</body>
</html>